version: '3'
services:
    web:
        image: nginx
        container_name: -PROJECT--Nginx
        restart: always
        environment:
            - DOMAIN=-DOMAIN-
            - TZ=Asia/Seoul
        ports:
            - -WEBPORT-:80
            - -SSLPORT-:443
        volumes:
            - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
            - ../../etc/nginx:/etc/nginx/conf.d
            - ../../web:/var/www/html
            - ../../etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - php
            - database
        networks:
            - docker-network
    php:
        image: cossia/board:0.1
        container_name: -PROJECT--PHP
        restart: always
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
            - ../../etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ../../web:/var/www/html
        depends_on:
            - database
        networks:
            - 'docker-network'

    database:
        image: mariadb:10.4
        container_name: -PROJECT--Mariadb
        restart: always
        environment:
            - MYSQL_DATABASE=-MYSQL_DATABASE-
            - MYSQL_ROOT_PASSWORD=-MYSQL_ROOT_PASSWORD-
            - MYSQL_USER=-MYSQL_USER-
            - MYSQL_PASSWORD=-MYSQL_PASSWORD-
            - TZ=Asia/Seoul
        ports:
            - -DBPORT-:3306
        volumes:
            - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
            - ../../database:/var/lib/mysql
        networks:
            - docker-network

networks:
  docker-network: 
    driver: bridge